version: "3.5"
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3005:3005"
    platform: linux/x86_64
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]
